WIP: PRINE-136 add monitoring endpoints
bet-smart-parking/smart-parking-backend pull request #75
Opened 2020-08-26 08:16 UTC by M16

2020-08-28 13:44 UTC, hirsch88 requested changes

2020-08-28 13:44 UTC, hirsch88 commented on functions/src/api/controller/monitoring.controller.ts
> +  async monitoring(): Promise<string> {
should the content of this method not be in a service?
it looks like business logic :-)

2020-08-28 13:45 UTC, hirsch88 commented on functions/src/api/controller/monitoring.controller.ts
> +  async monitoring(): Promise<string> {
Maybe also try to use async/await instead of .then

2020-08-31 12:13 UTC, prine commented on functions/src/api/controller/monitoring.controller.ts
> +  async monitoring(): Promise<string> {
I have updated it and its now an own service with asynch/await.

2020-08-31 12:30 UTC, merged

2020-09-04 07:47 UTC, bets-bal commented
:tada: This PR is included in version 1.16.0 :tada:

The release is available on [GitHub release](https://github.com/bet-smart-parking/smart-parking-backend/releases/tag/v1.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: